version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=8081
    ports:
      - "8081:8081"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=8082
    ports:
      - "8082:8082"